---
name: AnnoCPAN-Perldoc-SyncDB
version: 0.10
author:
  - 'Clotho Advanced Media, Inc. <cpan@clotho.com>'
abstract: Download the AnnoCPAN database
license: perl
build_requires:
  File::Spec: 0
  LWP::UserAgent: 0
  Test::More: 0
provides:
  AnnoCPAN::Perldoc::SyncDB:
    file: lib/AnnoCPAN/Perldoc/SyncDB.pm
    version: 0.10
generated_by: Module::Build version 0.2611
